spring.datasource.url=jdbc:postgresql://localhost:5432/campaign_loyalty
spring.datasource.username=yordanos
spring.datasource.password=kingdom
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=never
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
server.port=8080

campaign.admin.username=admin
campaign.admin.password=admin123
